<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kriteria extends CI_Controller
{
    public function __construct()
	{
		parent::__construct();

		//memperkenalkan ke controller
		$this->load->model('Kriteria_model');
		//Do your magic here
	}

	public function index()
	{
		$data['judul'] = 'Kriteria';
		$data['content'] = 'kriteria/v_kriteria';
		$data['isi_tabel'] = $this->Kriteria_model->get_all();
		$this->load->view('v_admin', $data);
	}

	public function tambah()
	{
		$data['judul'] = 'Form Tambah Kriteria';
		$data['content'] = 'kriteria/v_kriteria_add';		
		$this->load->view('v_admin', $data);
	}

	public function store()
	{
			//simpan data ke table database
			$data = array(
				'nama_kriteria' => $this->input->post('nama_kriteria')
				);
			$this->Kriteria_model->create($data);

			$this->session->set_flashdata('info', 'Data berhasil di tambah');

			redirect('kriteria','refresh');
		}

	public function edit($id='')
	{
		$data['isi_tabel'] = $this->Kriteria_model->get_id($id);

		if (!$data['isi_tabel']) {
			echo 'Halaman tidak ditemukan';
			return null;
		}

		$data['judul'] = 'Form Edit Kriteria';
		$data['content'] = 'kriteria/v_kriteria_edit';		
		$this->load->view('v_admin', $data);
	}

	public function update()
	{
		$id = $this->input->post('id_kriteria');
		$data = array(
			'nama_kriteria' => $this->input->post('nama_kriteria',TRUE)
			);
		$this->Kriteria_model->update($id, $data);
		$this->session->set_flashdata('info', 'Data berhasil di update');

		redirect('kriteria','refresh');
	}

	public function hapus($id='')
	{
		if ($id !== '') {
			$this->Kriteria_model->delete($id);
			$this->session->set_flashdata('info', 'Data berhasil di hapus');
			redirect('kriteria','refresh');
		}

		echo "Halaman tidak ditemukan";
		return null;
	}

}

/* End of file Kriteria.php */
/* Location: ./application/controllers/Kriteria.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-22 18:21:00 */
/* http://harviacode.com */