<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kriteria_model extends CI_Model
{
	public $order = 'ASC';
	private $tb_kriteria='kriteria';
	private $tb_alternatif='alternatif';          
	private $tb_kriteria_nilai='kriteria_nilai';
	
	function __construct()
    {
        parent::__construct();
		$this->load->library('m_db');
		
	}
	
	public function kriteria_data($where=array(),$orderK="id_kriteria ASC")
    { 		
	    $d=$this->m_db->get_data($this->tb_kriteria,$where,$orderK);
        return $d;
	}
	
	function kriteria_info($kriteriaID,$output)
    {
        $s=array('id_kriteria'=>$kriteriaID,);
        $item=$this->m_db->get_row($this->tb_kriteria,$s,$output);
        return $item;
    }

    function alternatif_data($where=array(),$orderK="id_alternatif ASC")
    {
        $d=$this->m_db->get_data($this->tb_alternatif,$where,$orderK);
        return $d;
    }

    // function alternatif_child($kriteriaID,$orderK="nama_alternatif")
    // {
    //     $s=array('id_kriteria'=>$kriteriaID,);
    //     $d=$this->alternatif_data($s,$orderK);
    //     return $d;
    // }

   public function get_all() 
	{
		return $this->db->get('kriteria')->result();
	}

	//select data berdasarkan primary key dari tabel
	public function get_id($param)
	{
		$this->db->where('id_kriteria', $param);
		return $this->db->get('kriteria')->row();
	}

	// untuk tambah data ke database
	public function create($data)
	{
		return $this->db->insert('kriteria', $data);
	}

	// update tabel berdasarkan id / primary key
	public function update($param_id, $param_data)
	{
		$this->db->where('id_kriteria', $param_id);
		return $this->db->update('kriteria', $param_data);
	}

	public function delete($param_id)
	{
		$this->db->where('id_kriteria', $param_id);
		return $this->db->delete('kriteria');
	}

}

/* End of file Kriteria_model.php */
/* Location: ./application/models/Kriteria_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-22 18:21:00 */
/* http://harviacode.com */